path: E:/EMCT/detector/datasets # dataset root dir
train: ../images/train
val: ../images/validation
# test: ./images/test # test images (relative to 'path') 4 images

names: ["Chainsaw", "Knife", "Rifle", "Axe", "Handgun"]
